trailingComma = "es5"
printWidth = 140

# Use 2 spaces for the indentation
tabWidth = 2

# Print semicolons at the ends of statements
semi = false

# Use single quotes instead of double quotes.
singleQuote = true

# Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).
bracketSameLine = true

# Include parentheses around a sole arrow function parameter.
arrowParens = "avoid"

# Use unix line endings
endOfLine = "lf"
