name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Sass
        run: sudo apt-get update && sudo apt-get install -y sass

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Site
        run: python serve.py --build-only

      # The new way of deploying to GitHub Pages, as of 2024
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: P1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
